### ISSUE TITLE
Can't change content item for content publishing element

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-marketing#10]
Step to reproduce:
1. Create new publishing element
2. Try to change content publishing item

The following exception occurs:

>   "exceptionMessage": "Multiplicity constraint violated. The role 'PublishingGroupContentItemEntity_PublishingGroup_Target' of the relationship 'VirtoCommerce.MarketingModule.Data.Repositories.PublishingGroupContentItemEntity_PublishingGroup' has multiplicity 1 or 0..1.",
"exceptionType": "System.InvalidOperationException",
"stacktrace": "
   at System.Data.Entity.Core.Objects.DataClasses.EntityReference`1.VerifyNavigationPropertyForAdd(IEntityWrapper wrapper)
   at System.Data.Entity.Core.Objects.EntityEntry.DetectChangesInRelationshipsOfSingleEntity()
   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChangesInNavigationProperties(IList`1 entries)
   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChanges()
   at System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
   at System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)
   at System.Data.Entity.DbSet.Add(Object entity)
   at VirtoCommerce.Platform.Data.Infrastructure.EFRepositoryBase.Add[T](T item) in E:\Programming\VirtoCommerce.Platform\VirtoCommerce.Platform.Data\Infrastructure\EFRepositoryBase.cs:line 201
   at VirtoCommerce.Platform.Data.Infrastructure.ServiceBase.<>c__DisplayClass1_0.<GetChangeTracker>b__1(Object x) in E:\Programming\VirtoCommerce.Platform\VirtoCommerce.Platform.Data\Infrastructure\ServiceBase.cs:line 30
   at VirtoCommerce.Platform.Core.Common.ObservableChangeTracker.<Attach>b__8_0(Object sender, NotifyCollectionChangedEventArgs args) in E:\Programming\VirtoCommerce.Platform\VirtoCommerce.Platform.Core\Common\ObservableChangeTracker.cs:line 36
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at VirtoCommerce.Platform.Core.Common.CollectionExtensions.<>c__DisplayClass7_0`1.<Patch>b__0(EntryState state, T x, T y) in E:\Programming\VirtoCommerce.Platform\VirtoCommerce.Platform.Core\Common\CollectionExtensions.cs:line 110
   at VirtoCommerce.Platform.Core.Common.CollectionExtensions.CompareTo[T](ICollection`1 source, ICollection`1 target, IEqualityComparer`1 comparer, Action`3 action) in E:\Programming\VirtoCommerce.Platform\VirtoCommerce.Platform.Core\Common\CollectionExtensions.cs:line 135
   at VirtoCommerce.Platform.Core.Common.CollectionExtensions.Patch[T](ICollection`1 source, ICollection`1 target, IEqualityComparer`1 comparer, Action`2 patch) in E:\Programming\VirtoCommerce.Platform\VirtoCommerce.Platform.Core\Common\CollectionExtensions.cs:line 118
   at VirtoCommerce.MarketingModule.Data.Model.DynamicContentPublishingGroupEntity.Patch(DynamicContentPublishingGroupEntity target) in E:\Programming\VirtoCommerce.Marketing\VirtoCommerce.MarketingModule.Data\Model\DynamicContentPublishingGroupEntity.cs:line 143
   at VirtoCommerce.MarketingModule.Data.Services.DynamicContentServiceImpl.SavePublications(DynamicContentPublication[] publications) in E:\Programming\VirtoCommerce.Marketing\VirtoCommerce.MarketingModule.Data\Services\DynamicContentServiceImpl.cs:line 168
   at VirtoCommerce.CacheModule.Data.Decorators.MarketingServicesDecorator.SavePublications(DynamicContentPublication[] publications) in E:\Programming\VirtoCommerce.Cache\VirtoCommerce.CacheModule.Data\Decorators\MarketingServicesDecorator.cs:line 102
   at VirtoCommerce.MarketingModule.Web.Controllers.Api.MarketingModuleDynamicContentController.UpdateDynamicContentPublication(DynamicContentPublication publication) in E:\Programming\VirtoCommerce.Marketing\VirtoCommerce.MarketingModule.Web\Controllers\Api\MarketingModuleDynamicContentController.cs:line 353
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Cors.CorsMessageHandler.<HandleCorsRequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Cors.CorsMessageHandler.<SendAsync>d__0.MoveNext()"
"

**Comment by OlegoO** [comment]
Same problem:
https://github.com/VirtoCommerce/vc-platform/issues/1082

**Comment by eMazeika** [comment]
Can't reproduce. @tatarincev , could this be fixed already?

**Comment by asvishnyakov** [comment]
@eMazeika gif from public demo

![](http://g.recordit.co/clt7HmehIX.gif)

**Comment by eMazeika** [comment]
@tatarincev this looks like quickfix somewhere in collections patching

**Comment by sansey2k** [comment]
@tatarincev Hi! Is there any chance to receive such bug fix in nearest time?

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-marketing/releases/v2.17.3
